language: erlang

sudo: false
os: linux
otp_release:
  - 20.0
  - 19.3
  - 18.3

script: rebar3 eunit
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
  - pip install codecov
script:
  - ./rebar3 compile
  - ./rebar3 xref
  - ./rebar3 eunit
  - ./rebar3 dialyzer
  - ./rebar3 edoc

after_success:
  - codecov
